export const STRINGS = {
  app_name: 'MomConnect',
  welcome: 'Welcome back',
  create_account: 'Create your account',
  email: 'Email',
  password: 'Password',
  full_name: 'Full name',
  login: 'Login',
  register: 'Register',
  please_wait: 'Please wait...',
  create_new: 'Create account',
  home: 'Home',
  community: 'Community',
  marketplace: 'Marketplace',
  dashboard: 'Dashboard',
  explore: 'Explore',
  profile: 'Profile',
  search: 'Search',
  menu: 'Menu',
  logout: 'Logout',
  settings: 'Settings',
  help: 'Help',
  about: 'About Us',
};